/**
 * AMT - gamification
 * The API specification for the AMT - gamification project. All endpoints are implicitely prefixed by __/api__ for the sake of readability.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * The info of a gamified application.
 */
export interface GamifiedApplication {
    /**
     * The unique name of the gamified application.
     */
    name?: string;

    /**
     * The password of the gamified application.
     */
    password?: string;

}
