/**
 * AMT - gamification
 * The API specification for the AMT - gamification project. All endpoints are implicitely prefixed by __/api__ for the sake of readability.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * An user doing various actions in an application.
 */
export interface User {
    /**
     * The username of the user.
     */
    username?: string;

    /**
     * The badges awarded to the user.
     */
    badges?: Array<models.Badge>;

    /**
     * The points received by the user.
     */
    points?: Array<models.PointsOnPointScale>;

}
